# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x05so101\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"3\n\tImagePair\x12\x12\n\ndepth_data\x18\x01 \x01(\x0c\x12\x12\n\ncolor_data\x18\x02 \x01(\x0c\"X\n\x10ImagePairRequest\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.so101.Request\x12#\n\timagePair\x18\x02 \x01(\x0b\x32\x10.so101.ImagePair\"[\n\x11ImagePairResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.so101.Response\x12#\n\timagePair\x18\x02 \x01(\x0b\x32\x10.so101.ImagePair\"\x16\n\x05Grasp\x12\r\n\x05grasp\x18\x01 \x03(\x02\"]\n\x0cGraspRequest\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.so101.Request\x12\x1b\n\x05grasp\x18\x02 \x01(\x0b\x32\x0c.so101.Grasp\x12\x0f\n\x07q_start\x18\x03 \x03(\x02\"O\n\rGraspResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.so101.Response\x12\x1b\n\x05grasp\x18\x02 \x01(\x0b\x32\x0c.so101.Grasp\"\x1a\n\nTrajectory\x12\x0c\n\x04traj\x18\x01 \x01(\x0c\"\x87\x01\n\x10PlanTrajectories\x12$\n\tpick_traj\x18\x01 \x01(\x0b\x32\x11.so101.Trajectory\x12%\n\nplace_traj\x18\x02 \x01(\x0b\x32\x11.so101.Trajectory\x12&\n\x0breturn_traj\x18\x03 \x01(\x0b\x32\x11.so101.Trajectory\"U\n\x11TrajectoryRequest\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.so101.Request\x12\x1f\n\x04traj\x18\x02 \x01(\x0b\x32\x11.so101.Trajectory\"p\n\x18PlanTrajectoriesResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.so101.Response\x12\x31\n\x10planTrajectories\x18\x02 \x01(\x0b\x32\x17.so101.PlanTrajectories2\xf6\x01\n\x08Pipeline\x12\x34\n\x08GetImage\x12\x0e.so101.Request\x1a\x18.so101.ImagePairResponse\x12\x39\n\x08GetGrasp\x12\x17.so101.ImagePairRequest\x1a\x14.so101.GraspResponse\x12?\n\x07GetPlan\x12\x13.so101.GraspRequest\x1a\x1f.so101.PlanTrajectoriesResponse\x12\x38\n\x0b\x45xecutePlan\x12\x18.so101.TrajectoryRequest\x1a\x0f.so101.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=25
  _globals['_REQUEST']._serialized_end=46
  _globals['_RESPONSE']._serialized_start=48
  _globals['_RESPONSE']._serialized_end=87
  _globals['_IMAGEPAIR']._serialized_start=89
  _globals['_IMAGEPAIR']._serialized_end=140
  _globals['_IMAGEPAIRREQUEST']._serialized_start=142
  _globals['_IMAGEPAIRREQUEST']._serialized_end=230
  _globals['_IMAGEPAIRRESPONSE']._serialized_start=232
  _globals['_IMAGEPAIRRESPONSE']._serialized_end=323
  _globals['_GRASP']._serialized_start=325
  _globals['_GRASP']._serialized_end=347
  _globals['_GRASPREQUEST']._serialized_start=349
  _globals['_GRASPREQUEST']._serialized_end=442
  _globals['_GRASPRESPONSE']._serialized_start=444
  _globals['_GRASPRESPONSE']._serialized_end=523
  _globals['_TRAJECTORY']._serialized_start=525
  _globals['_TRAJECTORY']._serialized_end=551
  _globals['_PLANTRAJECTORIES']._serialized_start=554
  _globals['_PLANTRAJECTORIES']._serialized_end=689
  _globals['_TRAJECTORYREQUEST']._serialized_start=691
  _globals['_TRAJECTORYREQUEST']._serialized_end=776
  _globals['_PLANTRAJECTORIESRESPONSE']._serialized_start=778
  _globals['_PLANTRAJECTORIESRESPONSE']._serialized_end=890
  _globals['_PIPELINE']._serialized_start=893
  _globals['_PIPELINE']._serialized_end=1139
# @@protoc_insertion_point(module_scope)
