# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_pb2 as pipeline__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImage = channel.unary_unary(
                '/so101.Pipeline/GetImage',
                request_serializer=pipeline__pb2.Request.SerializeToString,
                response_deserializer=pipeline__pb2.ImagePairResponse.FromString,
                _registered_method=True)
        self.GetGrasp = channel.unary_unary(
                '/so101.Pipeline/GetGrasp',
                request_serializer=pipeline__pb2.ImagePairRequest.SerializeToString,
                response_deserializer=pipeline__pb2.GraspResponse.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/so101.Pipeline/GetPlan',
                request_serializer=pipeline__pb2.GraspRequest.SerializeToString,
                response_deserializer=pipeline__pb2.PlanTrajectoriesResponse.FromString,
                _registered_method=True)
        self.ExecutePlan = channel.unary_unary(
                '/so101.Pipeline/ExecutePlan',
                request_serializer=pipeline__pb2.TrajectoryRequest.SerializeToString,
                response_deserializer=pipeline__pb2.Response.FromString,
                _registered_method=True)


class PipelineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGrasp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=pipeline__pb2.Request.FromString,
                    response_serializer=pipeline__pb2.ImagePairResponse.SerializeToString,
            ),
            'GetGrasp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGrasp,
                    request_deserializer=pipeline__pb2.ImagePairRequest.FromString,
                    response_serializer=pipeline__pb2.GraspResponse.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=pipeline__pb2.GraspRequest.FromString,
                    response_serializer=pipeline__pb2.PlanTrajectoriesResponse.SerializeToString,
            ),
            'ExecutePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlan,
                    request_deserializer=pipeline__pb2.TrajectoryRequest.FromString,
                    response_serializer=pipeline__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'so101.Pipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('so101.Pipeline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pipeline(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so101.Pipeline/GetImage',
            pipeline__pb2.Request.SerializeToString,
            pipeline__pb2.ImagePairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGrasp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so101.Pipeline/GetGrasp',
            pipeline__pb2.ImagePairRequest.SerializeToString,
            pipeline__pb2.GraspResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so101.Pipeline/GetPlan',
            pipeline__pb2.GraspRequest.SerializeToString,
            pipeline__pb2.PlanTrajectoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so101.Pipeline/ExecutePlan',
            pipeline__pb2.TrajectoryRequest.SerializeToString,
            pipeline__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
