"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
lcm-gen 1.5.2
"""

from .lcmt_so101_configuration import lcmt_so101_configuration as lcmt_so101_configuration
