"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_so101_configuration(object):
    __slots__ = ["q"]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_so101_configuration._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6d', *self.q[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_so101_configuration._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_so101_configuration._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_so101_configuration()
        self.q = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_so101_configuration in parents: return 0
        tmphash = (0x21f0a3981cf3355d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_so101_configuration._packed_fingerprint is None:
            lcmt_so101_configuration._packed_fingerprint = struct.pack(">Q", lcmt_so101_configuration._get_hash_recursive([]))
        return lcmt_so101_configuration._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

